### ISSUE TITLE
Настройка наценки

### ISSUE THREAD

**Issue by rinaf2021** [delosait-ru/delosait-ru.github.io#1]
- [x] в ячейках таблицы должны быть input: в них будут указываться значения

**Comment by rinaf2021** [comment]
Ipad

- [x] Слетел текст
![изображение](https://user-images.githubusercontent.com/45559069/134158825-5eb23f61-a5d4-4f3e-8a20-d27b88cf650d.png)

- [x] Высота блока 50 пикселей, а должен быть 28 + 9 пикселей отступ ниже
![изображение](https://user-images.githubusercontent.com/45559069/135249963-c92fbb39-f5f5-45b4-a699-21551b5f678d.png)

- [x] Знаю что в дизайне не прорисовано, но высота должна суммарно получаться 50, а тут 560
![изображение](https://user-images.githubusercontent.com/45559069/135250311-938d6696-52d9-4d0b-b27d-d948845f2ded.png)

**Comment by rinaf2021** [comment]
mobile

- [x] аналогично Ipad
![изображение](https://user-images.githubusercontent.com/45559069/134161204-8f025a6e-d832-46cc-bed4-cabe1a9841eb.png)

- [x] текст не должен переносится на другую строку
![изображение](https://user-images.githubusercontent.com/45559069/135250580-579776c7-6913-44d4-b2bf-375ef0bc8370.png)

**Comment by delosait-ru** [comment]
Исправлено
